version: '3.9'

services:
  app:
    image: microtrialfreelance
    build:
      context: .
      dockerfile: MicroTrialFreelance/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - micro-dev
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - micro-dev

networks:
  micro-dev:
    driver: bridge